name: 3.BranchBasedTrigger
pool: Mahakal1
trigger:
    branches:
        include:
            - main
            
parameters:
  - name: environment
    default: prod
    



variables:
  - name: WORK_DIR
    value: '$(System.DefaultWorkingDirectory)/environment/${{parameters.environment}}'


stages:
  - template: ScanStage.yml

  - template: PlanStage.yml
    parameters:
      environment: ${{ parameters.environment }}
    
  - template: ApplyStage.yml
    parameters:
      environment: ${{ parameters.environment }}
